version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gitsubmodule"
    directory: "/src/shadcn-svelte"
    schedule:
      interval: "monthly"